services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: test
      JWT_ACCESS_SECRET: access_secret
      JWT_REFRESH_SECRET: refresh_secret
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ["npx", "ts-node", "src/index.ts"]

volumes:
  pgdata: 